services:
  app:
    image: myapp-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    container_name: myapp-frontend-dev 
  server:
    image: myapp-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3001:3001
    container_name: myapp-backend-dev