services:
  app:
    image: myapp-frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    container_name: myapp-frontend
  server:
    image: myapp-backend
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3001:3001
    # enviroment for mongoDB connection comes from .env file
    container_name: myapp-backend